version: '3'
services:
  # attempting to run mongo from dock ((failed to access from js))
    db:
      image: mongo
      expose:
        - "27017"
      ports:
        - 27017:27017      
    app:
      build: .
      environment:
        DB_URL: ${DB_URL}
        DEBUG: ${DEBUG}
        NODE_ENV: ${NODE_ENV}
        TZ: ${TZ}
      ports:
        - 3000:3000
      restart: unless-stopped
